### ISSUE TITLE
使用总的 CPU 占用率的方法获取的数值几乎是恒定的

### ISSUE THREAD

**Issue by ySssssssss** [aozhimin/iOS-Monitor-Platform#2]
我在网上也没找到其他的api可以获取cpu的占用率,个人水平有限,所以还请作者帮忙看下是什么原因.

**Comment by aozhimin** [comment]
@ySssssssss 你采集的数值是多少？看你描述中说几乎是恒定的，说明还是会有细微波动的，所以关于 CPU 占用率几乎是恒定的，我的理解是否是因为你是在一个小 Demo 中测试，本身就没有什么消耗 CPU 的操作，所以 CPU 占用率也就没有多大波动呢？如果是这个问题，是否可以通过在测试中写一些消耗 CPU 的方法来测试代码来验证呢？

**Comment by ySssssssss** [comment]
@aozhimin 
我运行在SE上和6Ps上分别是18.xxxxxx和35.xxxxxx,手机不论做什么操作,数值的变动在小数点后4位之后,
同样的问题我在stackoverflow也看到了,但是并没有讨论的结果,这个是链接:
https://stackoverflow.com/questions/11842513/get-cpu-usage-at-runtime-ios?noredirect=1#

跟我有一样问题的讨论:
I tried with what you said, and I get some value for CPU usage. If I go and start some other apps which run in background or start playing music in the background CPU usage should go up right? But I get the same values i was getting earlier. – Manish Ahuja Aug 7 '12 at 10:02
  	 		  	 	
This method does not work at all. At fully loaded CPU, this always returns 6.89% for core 1 and 7.38% for core 0. – Legoless Nov 11 '14 at 9:16

**Comment by aozhimin** [comment]
@ySssssssss 我们性能监控 SDK 已经开发完成，并且我对将我们的 SDK 嵌入到一些 App 如手Q和手淘等，做过详细的测试，没有发现你说的这个问题，测试报告的地址：https://github.com/aozhimin/iOS-Performance-Report

**Comment by aozhimin** [comment]
@ySssssssss 方便将你获取 CPU 占用率，以及如何使用的那部分代码贴出来吗？我这边帮你看下。

**Comment by ySssssssss** [comment]
@aozhimin 
emmm..测试报告是获取当前app占用cpu

我使用的代码是这部分

总的 CPU 占用率

而获取整个设备的 CPU 占用率如下：

static NSUInteger const kMaxPercent = 100;

+ (CGFloat)cpuUsage {
    CGFloat cpuUsage = 0;
    processor_info_array_t _cpuInfo, _prevCPUInfo = nil;
    mach_msg_type_number_t _numCPUInfo, _numPrevCPUInfo = 0;
    unsigned _numCPUs;
    NSLock *_cpuUsageLock;
    
    int _mib[2U] = {CTL_HW, HW_NCPU};
    size_t _sizeOfNumCPUs = sizeof(_numCPUs);
    int _status = sysctl(_mib, 2U, &_numCPUs, &_sizeOfNumCPUs, NULL, 0U);
    if (_status)
        _numCPUs = 1;
    
    _cpuUsageLock = [[NSLock alloc] init];
    
    natural_t _numCPUsU = 0U;
    kern_return_t err = host_processor_info(mach_host_self(), PROCESSOR_CPU_LOAD_INFO, &_numCPUsU, &_cpuInfo, &_numCPUInfo);
    if (err == KERN_SUCCESS) {
        [_cpuUsageLock lock];
        
        for (unsigned i = 0U; i < _numCPUs; ++i) {
            CGFloat _inUse, _total = 0;
            if (_prevCPUInfo) {
                _inUse = (
                          (_cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_USER]   - _prevCPUInfo[(CPU_STATE_MAX * i) + CPU_STATE_USER])
                          + (_cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_SYSTEM] - _prevCPUInfo[(CPU_STATE_MAX * i) + CPU_STATE_SYSTEM])
                          + (_cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_NICE]   - _prevCPUInfo[(CPU_STATE_MAX * i) + CPU_STATE_NICE])
                          );
                _total = _inUse + (_cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_IDLE] - _prevCPUInfo[(CPU_STATE_MAX * i) + CPU_STATE_IDLE]);
            } else {
                _inUse = _cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_USER] + _cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_SYSTEM] + _cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_NICE];
                _total = _inUse + _cpuInfo[(CPU_STATE_MAX * i) + CPU_STATE_IDLE];
            }
            
            if (_total != 0) {
                cpuUsage += _inUse / _total;
            }
        }
        
        [_cpuUsageLock unlock];
        if (_prevCPUInfo) {
            size_t prevCpuInfoSize = sizeof(integer_t) * _numPrevCPUInfo;
            vm_deallocate(mach_task_self(), (vm_address_t)_prevCPUInfo, prevCpuInfoSize);
        }
        return cpuUsage * kMaxPercent ;
    } else {
        return -1;
    }
}
上述方法大致思路是先计算出每个 CPU 核心的占用率，然后将所有 CPU 核心的占用率相加得到设备总的 CPU 占用率，这主要参考 top 命令，它在计算多核 CPU 的占用率时，是把每个核的 CPU 占用率求和。

**Comment by aozhimin** [comment]
@ySssssssss 好的，稍等下，我现在拉取一份报告给你看

**Comment by ySssssssss** [comment]
@aozhimin 十分感谢你

**Comment by aozhimin** [comment]
@ySssssssss 这是测试手淘的数据，`totalCPURate` 确实变化不大，我查下问题出在哪里
totalCPURate | appCPURate
-- | --
19.83191027322256 | 66.10000007599592
19.83218247549417 | 32.89999907463789
19.83254745452505 | 27.69999957829714
19.8328990520483 | 31.60000042617321
19.83301122171272 | 7.699999749660492
19.8336411876365 | 81.19999849796295
19.83386246250572 | 47.10000071674585
19.83426391094043 | 47.80000087618828
19.83458819925035 | 61.00000192224979
19.83487617819364 | 66.40000071376562
19.83499225391794 | 20.40000074356794
19.83540580599981 | 71.10000078380108
19.8356095409361 | 16.40000066906214
19.83591292428321 | 71.90000197291374
19.83597534111268 | 8.900000110268593

**Comment by ySssssssss** [comment]
@aozhimin 谢谢!

**Comment by aozhimin** [comment]
我还应该谢谢你发现这个问题，之前没太注意这个指标

**Comment by aozhimin** [comment]
@ySssssssss 问题基本已经确定，原先的那种做法获取的 CPU 占用率不变的原因是因为 `_cpuInfo` `_prevCPUInfo` 等变量应该是成员变量，而不是局部变量，否则代码的执行逻辑会出现问题，导致每次计算的值基本不变，而大部分文章没有去验证做法的正确性，包括 YYCategories 这个库里面 UIDevice 的 那个 `YYAdd` 的 Category 也是采取这种做法，即使把那些变量换成局部变量，占用率确实会不断变化，但是大部分时间都在100%以上，有可能是因为这种方法算的是多核总共 CPU 占用率的原因，另外找到另外一种获取 CPU 占用率的方法是通过 `host_statistics` 在 mach kernel 层去计算设备的 CPU 占用率，具体代码如下：
```
- (CGFloat)cpuUsage {
    kern_return_t kr;
    mach_msg_type_number_t count;
    static host_cpu_load_info_data_t previous_info = {0, 0, 0, 0};
    host_cpu_load_info_data_t info;
    
    count = HOST_CPU_LOAD_INFO_COUNT;
    
    kr = host_statistics(mach_host_self(), HOST_CPU_LOAD_INFO, (host_info_t)&info, &count);
    if (kr != KERN_SUCCESS) {
        return -1;
    }
    
    natural_t user   = info.cpu_ticks[CPU_STATE_USER] + info.cpu_ticks[CPU_STATE_NICE]
                       - previous_info.cpu_ticks[CPU_STATE_USER] - previous_info.cpu_ticks[CPU_STATE_NICE];
    natural_t system = info.cpu_ticks[CPU_STATE_SYSTEM] - previous_info.cpu_ticks[CPU_STATE_SYSTEM];
    natural_t idle   = info.cpu_ticks[CPU_STATE_IDLE] - previous_info.cpu_ticks[CPU_STATE_IDLE];
    natural_t total  = user + system + idle;
    previous_info    = info;
    
    return (user + system) * 100.0 / total;
}
```

在 App Store 上的一些性能监控的工具应用都是采取这种方式的包括简易系统状态和 Battery Memory System Status Monitor

下面是使用后面一种方法测试后得到的数据：

totalCPURate | appCPURate
-- | --
37.3134328358209 | 0.6000000238418579
64.19753086419753 | 0.6000000238418579
55.83756345177665 | 0.7000000476837158
42.23706176961603 | 0.7000000476837158

**Comment by aozhimin** [comment]
@ySssssssss 文章已更新，同时经测试，上面第二种方式与系统计算出来的值比较吻合，建议使用。

**Comment by ySssssssss** [comment]
@aozhimin 真的感谢你的悉心答复,祝你工作顺利!

**Comment by aozhimin** [comment]
[微笑] 也祝你工作顺利

**Comment by aozhimin** [comment]
好的，也祝你工作顺利~

**Comment by zhihuitang** [comment]
这里的CPU占用率怎么区分system和user的啊?

**Comment by ihewro** [comment]
这两种计算cpu方式应该都是可行的，前者通过计算每个processor的cpu，然后累加，最后应该需要除以核心的数目
而后者计算的是系统整体的cpu占用，不需要除以核心
